### ISSUE TITLE
Something wrong with getMapObjects

### ISSUE THREAD

**Issue by oujinlong** [enzosv/pokemonGoAutoIV#1]
empty response for getMapObjects
how can i deal with....?
Thanks

**Comment by enzosv** [comment]
I'm sorry, what do you mean? This app doesn't get any map objects.

**Comment by oujinlong** [comment]
that is about the API method getMapObjects

**Comment by enzosv** [comment]
Ah, for issues with the API, please forward your concerns to https://github.com/lsapan/pgoapi-swift. I'm merely using this to retrieve user's pokemon data
